apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend
  namespace: krakend-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: traefik
  rules:
  - host: api-dev.krockysphere.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: krakend
            port:
              number: 8080
  tls:
  - hosts:
    - api-dev.krockysphere.com
    secretName: krakend-dev-tls
