apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend
  namespace: krakend-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Enable Authentik authentication for prod
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd,krakend-prod-ratelimit@kubernetescrd
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  ingressClassName: traefik
  rules:
  - host: api.krockysphere.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: krakend
            port:
              number: 8080
  tls:
  - hosts:
    - api.krockysphere.com
    secretName: krakend-prod-tls
